import { lstat, mkdir, readFile, readdir, rmdir, unlink } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createDirectoryAtomic, writeJsonAtomic, writeTextAtomic } from "./io.mjs";
import { renderSkillMarkdown } from "./frontmatter.mjs";
import { INTENT_ARRAYS, selectProfile, validateIntent } from "./profiles.mjs";
import { createObligationLedger } from "./obligations.mjs";
import {
  GUIDANCE_INDEX_MARKER, GUIDANCE_TOPIC_MARKER, guidanceTopicPath, inlineJudgmentPoints, judgmentTopics,
  renderGuidanceEntry, renderGuidanceIndex, renderGuidanceTopic
} from "./guidance.mjs";

const AUTHORING_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
export const P2_PACKAGE_GITATTRIBUTES = "* -text\n";
const SIMPLE_ADAPTIVE_JUDGMENT = "Use judgment for novel cases. If repeated small fixes stop moving the user's requested result closer, step back to that result and reconsider the approach or ask the user instead of adding exceptions. Before changing the work to satisfy a failing check, confirm that the check and its setup observe the stated outcome. Preserve the stated meaning, exact formats, irreversible boundaries, and completion evidence while doing so.";
const P2_ADAPTIVE_JUDGMENT = "Use judgment only within domain work that the current Decision leaves open. If repeated attempts stop converging, pause that work and resolve the uncertainty with the user; never skip, reorder, or substitute for the Decision, its evidence requirements, or the steps above. Before changing domain work to satisfy a failing check, confirm that the check and its setup observe the Decision's required outcome.";

export async function generatePackage({ intent, output, requestedProfile = "auto", replace = false, finalize = null }) {
  const issues = validateIntent(intent);
  if (issues.length > 0) throw new Error(`Intent brief is invalid:\n- ${issues.join("\n- ")}`);
  const selection = selectProfile(intent, requestedProfile);
  const target = resolve(output);
  await createDirectoryAtomic(target, async (stage) => {
    await writeAuthoringState(stage, intent, selection);
    if (selection.profile === "p0") await generateP0(stage, intent);
    else if (selection.profile === "p1") await generateP1(stage, intent);
    else await generateP2Source(stage, intent);
    if (finalize) await finalize(stage, selection);
  }, { replace, replaceNonEmpty: false });
  return { root: target, ...selection };
}

export async function generateP0(root, intent) {
  await writeSimplePackage(root, intent, "p0");
}

export async function generateP1(root, intent) {
  await writeSimplePackage(root, intent, "p1");
  await mkdir(join(root, "scripts"), { recursive: true });
  await writeTextAtomic(join(root, "scripts", "run.mjs"), `#!/usr/bin/env node\n// @skill-rails scaffold: replace this body with the approved deterministic helper and tests.\nprocess.stderr.write("SR_P1_SCAFFOLD: deterministic helper is not implemented; complete authoring before use.\\n");\nprocess.exitCode = 2;\n`);
  if ((intent.exact_formats ?? []).length > 0) {
    await mkdir(join(root, "templates"), { recursive: true });
    await writeTextAtomic(join(root, "templates", "output.md"), `# Output\n\n{{content}}\n`);
  }
}

export async function generateP2Source(root, intent) {
  await mkdir(join(root, "collectors"), { recursive: true });
  await mkdir(join(root, "fixtures", "lint"), { recursive: true });
  await mkdir(join(root, "templates"), { recursive: true });
  await mkdir(join(root, "references"), { recursive: true });
  await writeTextAtomic(join(root, "spec.mjs"), p2Spec(intent));
  await writeTextAtomic(join(root, "body.md"), p2Body(intent));
  await writeTextAtomic(join(root, "collectors", "index.mjs"), "export const collectors = Object.freeze({});\nexport const snapshotBasis = null;\n");
  await writeTextAtomic(join(root, "templates", "result.md"), "# Result\n\n{{summary}}\n");
  await writeJsonAtomic(join(root, "fixtures", "scenarios.json"), p2Scenarios());
  await writeJsonAtomic(join(root, "fixtures", "formats.json"), []);
  await writeJsonAtomic(join(root, "fixtures", "lint", "manifest.json"), { schema: "skill-rails/lint-mutations/1", cases: lintMutationCases() });
}

export async function writeGeneratedSkillBootstrap(root, intent) {
  await assertP2PackageGitAttributes(root, { manifestOwned: true });
  await writeTextAtomic(join(root, ".gitattributes"), P2_PACKAGE_GITATTRIBUTES);
  const body = `<!-- @generated by Skill Rails; edit canonical sources and rebuild -->\n# ${title(intent.name)}\n\nResolve \`<skill-root>\` to this SKILL.md directory. In Claude Code use \`${"${CLAUDE_SKILL_DIR}"}\`; in Codex use the absolute skill path from skill metadata. Resolve \`<project>\` to the working project and \`<trace-dir>\` to a writable directory outside the installed skill.\n\n1. Run \`node "<skill-root>/scripts/skill-rails/run.mjs" enter --skill "<skill-root>"\` unless this context has already processed the returned enter hash.\n2. If the current task explicitly identifies a complete saved stage-result file as the current Decision for this installed skill and project, and confirms that neither the skill package nor the covered project state has changed since it was produced, step 1 still applies; skip the stage call and continue at step 3 with that exact file. Do not infer those conditions from a discovered file or conversation memory. If any condition is absent or uncertain, run \`node "<skill-root>/scripts/skill-rails/run.mjs" stage --skill "<skill-root>" --project "<project>" --trace-dir "<trace-dir>" --json\` and save the complete JSON stage result. Supply only requested \`--judged field=value\` or \`--decided field=value\` values. When the current task or role already identifies one project-relative file target that collectors need, add \`--target "<path>"\`; never infer a target, and omit the option when the package does not need one.\n3. Stop on a diagnostic or stale snapshot. Otherwise follow only the current Decision body, \`stage_artifacts\`, and ordered effects, processing every effect in order through the final terminal; ASK, WAIT, BLOCK, DONE, and ROUTE stop only when reached after all preceding effects. Resolve every \`stage_artifacts[].path\` from \`<project>\`; a \`READ\` effect's \`path\` argument names package guidance and resolves from \`<skill-root>\`. Do not infer replacement paths from collector or authoring files.\n4. Attach claims with \`record --decision <stage-result.json> --type <effect_claimed|proof_recorded|receipt_recorded> --data <json>\`. For a declared file proof, use \`--type artifact_verified --data '{"reference":"<proof.reference>"}' --artifact "<path>" --project "<project>"\`, replacing \`<proof.reference>\` with the matching proof reference from the current Decision. The stage-result file supplies its run id and trace path.\n5. Run \`align --decision <stage-result.json>\`. Record and alignment evidence is bound to the exact Decision in that file. Missing or agent-only evidence remains unproven; never upgrade it to success.\n6. If \`reinvoke\` is set, invoke stage again with the same \`--run-id\` after effects and save the new stage result. Resupply \`--target\` only when the current task or role still identifies that target. Evidence and alignment for the earlier Decision do not automatically carry to the new Decision.\n\n${P2_ADAPTIVE_JUDGMENT}\n\nThe runtime decides and verifies; it never performs domain effects. Never edit generated files listed in \`.generated.json\` directly.`;
  await writeTextAtomic(join(root, "SKILL.md"), renderSkillMarkdown({ name: intent.name, description: intent.description, body }));
  await writeOpenAiAdapter(root, intent, true);
}

export async function assertP2PackageGitAttributes(root, options = {}) {
  const path = join(resolve(root), ".gitattributes");
  let entry;
  try { entry = await lstat(path); }
  catch (error) { if (error.code === "ENOENT") return; throw error; }
  if (!entry.isFile()) throw packageGitAttributesCollision("the existing entry is not a regular file");
  const source = await readFile(path);
  const canonical = Buffer.from(P2_PACKAGE_GITATTRIBUTES, "utf8");
  if (!source.equals(canonical)) throw packageGitAttributesCollision("the existing file does not have the canonical bytes '* -text\\n'");
  if (!options.manifestOwned && !options.allowOwnershipTransfer) {
    throw packageGitAttributesCollision("the existing canonical file is not owned by the build manifest; rerun with --repair-generated to transfer ownership explicitly");
  }
}

function packageGitAttributesCollision(reason) {
  const error = new Error(`SR_GENERATED_COLLISION: .gitattributes is reserved for generated P2 package byte ownership, but ${reason}; the file was not overwritten or merged.`);
  error.code = "SR_GENERATED_COLLISION";
  return error;
}

async function writeAuthoringState(root, intent, selection) {
  await mkdir(join(root, ".skill-rails"), { recursive: true });
  await writeJsonAtomic(join(root, ".skill-rails", "intent.json"), intent);
  await writeJsonAtomic(join(root, ".skill-rails", "profile-decision.json"), {
    schema: "skill-rails/profile-decision/1",
    profile: selection.profile,
    explicit: selection.explicit,
    signals: selection.signals,
    warning: selection.profile === "p2" ? "This is a structurally valid design scaffold, not evidence that user-specific semantics are complete." : null
  });
  await writeJsonAtomic(join(root, ".skill-rails", "obligation-ledger.json"), createObligationLedger(intent, selection.profile));
  await writeJsonAtomic(join(root, ".skill-rails", "eval-cases.json"), createEvalCases(intent));
}

export function createEvalCases(intent) {
  return [
    ...(intent.use_cases ?? []).map((task, index) => ({
      id: `positive-${index + 1}`, task, should_trigger: true,
      expected_obligations: [...intent.outputs, ...intent.external_dependencies.map((item) => `Confirm dependency: ${item}`)],
      forbidden_actions: intent.irreversible_boundaries.map((item) => `Perform without explicit authority: ${item}`),
      acceptance: intent.completion_evidence.length > 0 ? [...intent.completion_evidence] : [...intent.outputs]
    })),
    ...(intent.near_misses ?? []).map((task, index) => ({ id: `near-miss-${index + 1}`, task, should_trigger: false, expected_obligations: [], forbidden_actions: [], acceptance: [] }))
  ];
}

async function writeOpenAiAdapter(root, intent, generated = false) {
  await mkdir(join(root, "agents"), { recursive: true });
  await writeTextAtomic(join(root, "agents", "openai.yaml"), renderOpenAiAdapter(intent, generated));
}

export function renderOpenAiAdapter(intent, generated = false) {
  const header = generated ? "# @generated by Skill Rails\n" : "";
  return `${header}interface:\n  display_name: ${JSON.stringify(title(intent.name))}\n  short_description: ${JSON.stringify(shortDescription(intent.description))}\n  default_prompt: ${JSON.stringify(`Use $${intent.name} for this task and follow its evidence boundary.`)}\npolicy:\n  allow_implicit_invocation: true\n`;
}

export async function writeSimplePackage(root, intent, profile, options = {}) {
  if (options.refresh) await removeOwnedGuidance(root);
  await writeTextAtomic(join(root, "SKILL.md"), renderSimpleSkillMarkdown(intent, profile));
  await writeOpenAiAdapter(root, intent);
  const topics = judgmentTopics(intent);
  if (topics.length === 0) return;
  await writeTextAtomic(join(root, "references", "guidance-index.md"), renderGuidanceIndex(topics));
  for (const topic of topics) await writeTextAtomic(join(root, guidanceTopicPath(topic.id)), renderGuidanceTopic(topic));
}

export async function assertSimpleProjectionOwnership(root, intent, profile) {
  const expected = new Map([
    ["SKILL.md", renderSimpleSkillMarkdown(intent, profile)],
    ["agents/openai.yaml", renderOpenAiAdapter(intent)]
  ]);
  const topics = judgmentTopics(intent);
  if (topics.length > 0) expected.set("references/guidance-index.md", renderGuidanceIndex(topics));
  for (const topic of topics) expected.set(guidanceTopicPath(topic.id), renderGuidanceTopic(topic));
  for (const [local, source] of expected) {
    let actual;
    try { actual = await readFile(join(root, ...local.split("/")), "utf8"); }
    catch (error) { throw new Error(`SR_SIMPLE_OWNERSHIP: canonical projection is unavailable: ${local}: ${error.message}`); }
    if (normalizeNewlines(actual) !== normalizeNewlines(source)) throw new Error(`SR_SIMPLE_OWNERSHIP: ${local} differs from the intent-derived projection; preserve the change in intent or another owned file before maintenance.`);
  }
}

async function removeOwnedGuidance(root) {
  const indexPath = join(root, "references", "guidance-index.md");
  try {
    const source = await readFile(indexPath, "utf8");
    if (!source.includes(GUIDANCE_INDEX_MARKER)) throw new Error("SR_GUIDANCE_OWNERSHIP: refusing to replace an unowned guidance index.");
    await unlink(indexPath);
  } catch (error) { if (error.code !== "ENOENT") throw error; }
  const directory = join(root, "references", "guidance");
  let entries;
  try { entries = await readdir(directory, { withFileTypes: true }); }
  catch (error) { if (error.code === "ENOENT") return; throw error; }
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    const path = join(directory, entry.name);
    const source = await readFile(path, "utf8");
    if (source.includes(GUIDANCE_TOPIC_MARKER)) await unlink(path);
  }
  try { await rmdir(directory); }
  catch (error) { if (error.code !== "ENOTEMPTY" && error.code !== "ENOENT") throw error; }
}

function p2Spec(intent) {
  return `export const SPEC = { version: "5", id: ${JSON.stringify(intent.name)}, profile: "single", imports: [] };
export const OBSERVATIONS = {
  "authoring.readiness": { decided: true, domain: ["ready", "needs-design", "complete"] }
};
export const FORMATS = {};
export const TEMPLATES = {
  result: { file: "templates/result.md", fields: { summary: "block" }, sections: [] }
};
export const ORDERS = {};
export const OWNERSHIP = {};
export const GUARDS = [];
export const STAGES = [
  { id: "operate", reads: ["authoring.readiness"], acceptsUnknown: [], done: s => s.authoring.readiness === "complete", needs: ["authoring.readiness"], reentry: "rejudge", branches: {
    ready: [["REPORT", { template: "result" }], "DONE"],
    "needs-design": ["BLOCK"]
  }, body: "stage: operate" }
];
export const TABLES = {};
export const ARTIFACTS = {};
export const ROLES = {};
export const READ_FIRST = [{ body: "why: purpose" }];
export const DECLARATIONS = {
  profile: { value: "p2", consumer: "build:profile" }
};
export const DEFERRED = [{ id: "replace-authoring-scaffold", rule: "Replace the generic readiness stage with approved user-specific obligations.", collector: "none", fixture: "fixtures/scenarios.json", owner: ${JSON.stringify(intent.name)}, until: "before-behavior-verification" }];
`;
}

function p2Body(intent) {
  return `# ${title(intent.name)}\n\n## why: purpose\n\n${intent.problem.trim()}\n\n## stage: operate\n\nJudgment: authoring.readiness is one of ready, needs-design, or complete. Confirm that the user-specific contract has replaced the generic authoring scaffold before treating the skill as behavior-complete.\n\nWhy: Structural validity alone cannot prove that the user's intended behavior was preserved.\n`;
}

function p2Scenarios() {
  return [
    { id: "ready", s: {}, decided: { "authoring.readiness": "ready" }, expect: { stage: "operate", status: "DONE", effects: ["REPORT", "DONE"] }, cover: ["stage:operate", "branch:operate/ready"] },
    { id: "needs-design", s: {}, decided: { "authoring.readiness": "needs-design" }, expect: { stage: "operate", status: "BLOCK" }, cover: ["branch:operate/needs-design"] },
    { id: "complete", s: {}, decided: { "authoring.readiness": "complete" }, expect: { stage: null, status: "DONE" }, cover: [] }
  ];
}

function lintMutationCases() {
  const operations = [
    "extra-export", "ambient-authority", "observation-source", "invalid-domain", "reads-mismatch", "table-default",
    "stage-contract", "body-section", "body-duplicate-procedure", "stage-signature", "artifact-readers", "template-placeholder",
    "role-state-effect", "language-parity", "fixture-coverage", "format-domain", "deferred-shape", "mutation-manifest", "unsafe-bypass"
  ];
  return [
    ...operations.map((operation, index) => ({ id: `negative-L${index}`, expected_code: `L${index}`, mutation: { operation } })),
    { id: "negative-L15-format-golden", expected_code: "L15", mutation: { operation: "format-golden" } }
  ];
}

export function renderSimpleSkillMarkdown(intent, profile) {
  const sections = renderIntentSections(intent);
  const progressive = judgmentTopics(intent).length > 0 ? `\n\n${renderGuidanceEntry()}` : "";
  const helperGate = profile === "p1"
    ? "\n\n## Helper gate\n\nIf `node <this-skill>/scripts/run.mjs` emits `SR_P1_SCAFFOLD`, authoring is incomplete: stop, replace the marked P1 helper scaffold, and add golden tests before use. Resolve `<this-skill>` from this SKILL.md location."
    : "";
  const body = `# ${title(intent.name)}\n\n${intent.problem.trim()}${sections ? `\n\n${sections}` : ""}${helperGate}${progressive}\n\n## Workflow\n\n1. Confirm that the request fits the stated use cases and not a near miss.\n2. Work from the declared inputs and produce only the declared outputs.\n3. Respect every boundary, state-dependent rule, exact format, and external dependency shown above.\n4. Claim completion only with the declared evidence.\n\n${SIMPLE_ADAPTIVE_JUDGMENT}`;
  return renderSkillMarkdown({ name: intent.name, description: intent.description, body });
}

function renderIntentSections(intent) {
  return INTENT_ARRAYS.map((field) => {
    const items = field === "judgment_points" ? inlineJudgmentPoints(intent) : intent[field];
    return items.length > 0 ? `## ${title(field.replaceAll("_", "-"))}\n\n${bullets(items)}` : null;
  }).filter(Boolean).join("\n\n");
}

function bullets(items = []) { return items.map((item) => `- ${item}`).join("\n"); }
function normalizeNewlines(text) { return String(text).replace(/\r\n/g, "\n"); }
function shortDescription(text) { return String(text).replace(/\s+/g, " ").trim(); }
function title(name) { return String(name).split("-").map((part) => part ? part[0].toUpperCase() + part.slice(1) : part).join(" "); }

export { AUTHORING_ROOT };
