import { mkdir, readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createDirectoryAtomic, writeJsonAtomic, writeTextAtomic } from "./io.mjs";
import { renderSkillMarkdown } from "./frontmatter.mjs";
import { INTENT_ARRAYS, selectProfile, validateIntent } from "./profiles.mjs";
import { createObligationLedger } from "./obligations.mjs";

const AUTHORING_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");

export async function generatePackage({ intent, output, requestedProfile = "auto", replace = false, finalize = null }) {
  const issues = validateIntent(intent);
  if (issues.length > 0) throw new Error(`Intent brief is invalid:\n- ${issues.join("\n- ")}`);
  const selection = selectProfile(intent, requestedProfile);
  const target = resolve(output);
  await createDirectoryAtomic(target, async (stage) => {
    await writeAuthoringState(stage, intent, selection);
    if (selection.profile === "p0") await generateP0(stage, intent);
    else if (selection.profile === "p1") await generateP1(stage, intent);
    else await generateP2Source(stage, intent);
    if (finalize) await finalize(stage, selection);
  }, { replace, replaceNonEmpty: false });
  return { root: target, ...selection };
}

export async function generateP0(root, intent) {
  await writeTextAtomic(join(root, "SKILL.md"), renderSkillMarkdown({
    name: intent.name,
    description: intent.description,
    body: `# ${title(intent.name)}\n\n${intent.problem}\n\n${renderIntentSections(intent)}\n\n## Workflow\n\n${workflowLines(intent).join("\n")}\n\nUse judgment for novel cases. Preserve the stated meaning, do not cross irreversible boundaries without explicit authority, and do not claim completion without the evidence named in the intent brief.`
  }));
  await writeOpenAiAdapter(root, intent);
  await writeReference(root, intent);
}

export async function generateP1(root, intent) {
  await generateP0(root, intent);
  await mkdir(join(root, "scripts"), { recursive: true });
  await writeTextAtomic(join(root, "scripts", "run.mjs"), `#!/usr/bin/env node\n// @skill-rails scaffold: replace this body with the approved deterministic helper and tests.\nprocess.stderr.write("SR_P1_SCAFFOLD: deterministic helper is not implemented; complete authoring before use.\\n");\nprocess.exitCode = 2;\n`);
  if ((intent.exact_formats ?? []).length > 0) {
    await mkdir(join(root, "templates"), { recursive: true });
    await writeTextAtomic(join(root, "templates", "output.md"), `# Output\n\n{{content}}\n`);
  }
  const skill = await readFile(join(root, "SKILL.md"), "utf8");
  await writeTextAtomic(join(root, "SKILL.md"), skill.replace(
    "Use judgment for novel cases.",
    "Before first use, replace the marked P1 helper scaffold and add golden tests. Until then, stop on `SR_P1_SCAFFOLD`. Run `node <this-skill>/scripts/run.mjs` only after that gate passes. Resolve `<this-skill>` from this SKILL.md location.\n\nUse judgment for novel cases."
  ));
}

export async function generateP2Source(root, intent) {
  await mkdir(join(root, "collectors"), { recursive: true });
  await mkdir(join(root, "fixtures", "lint"), { recursive: true });
  await mkdir(join(root, "templates"), { recursive: true });
  await mkdir(join(root, "references"), { recursive: true });
  await writeTextAtomic(join(root, "spec.mjs"), p2Spec(intent));
  await writeTextAtomic(join(root, "body.md"), p2Body(intent));
  await writeTextAtomic(join(root, "collectors", "index.mjs"), "export const collectors = Object.freeze({});\nexport const snapshotBasis = null;\n");
  await writeTextAtomic(join(root, "templates", "result.md"), "# Result\n\n{{summary}}\n");
  await writeTextAtomic(join(root, "references", "purpose.md"), `# Purpose\n\n${intent.problem.trim()}\n`);
  await writeJsonAtomic(join(root, "fixtures", "scenarios.json"), p2Scenarios());
  await writeJsonAtomic(join(root, "fixtures", "formats.json"), []);
  await writeJsonAtomic(join(root, "fixtures", "lint", "manifest.json"), { schema: "skill-rails/lint-mutations/1", cases: lintMutationCases() });
}

export async function writeGeneratedSkillBootstrap(root, intent) {
  const body = `<!-- @generated by Skill Rails; edit canonical sources and rebuild -->\n# ${title(intent.name)}\n\nResolve \`<skill-root>\` to this SKILL.md directory. In Claude Code use \`${"${CLAUDE_SKILL_DIR}"}\`; in Codex use the absolute skill path from skill metadata. Resolve \`<project>\` to the working project and \`<trace-dir>\` to a writable directory outside the installed skill.\n\n1. Run \`node "<skill-root>/scripts/skill-rails/run.mjs" enter --skill "<skill-root>"\` unless this context has already processed the returned enter hash.\n2. Run \`node "<skill-root>/scripts/skill-rails/run.mjs" stage --skill "<skill-root>" --project "<project>" --trace-dir "<trace-dir>" --json\` and save the complete JSON stage result. Supply only requested \`--judged field=value\` or \`--decided field=value\` values.\n3. Stop on a diagnostic, stale snapshot, BLOCK, ASK, or WAIT. Otherwise follow only the current Decision body and ordered effects.\n4. Attach claims with \`record --decision <stage-result.json> --type <effect_claimed|proof_recorded|receipt_recorded> --data <json>\`. For a declared file proof, use \`--type artifact_verified --artifact <path> --project "<project>"\`. The stage-result file supplies its run id and trace path.\n5. Run \`align --decision <stage-result.json>\`. Missing or agent-only evidence remains unproven; never upgrade it to success.\n6. If \`reinvoke\` is set, invoke stage again with the same \`--run-id\` after effects.\n\nThe runtime decides and verifies; it never performs domain effects. Never edit generated files listed in \`.generated.json\` directly.`;
  await writeTextAtomic(join(root, "SKILL.md"), renderSkillMarkdown({ name: intent.name, description: intent.description, body }));
  await writeOpenAiAdapter(root, intent, true);
}

async function writeAuthoringState(root, intent, selection) {
  await mkdir(join(root, ".skill-rails"), { recursive: true });
  await writeJsonAtomic(join(root, ".skill-rails", "intent.json"), intent);
  await writeJsonAtomic(join(root, ".skill-rails", "profile-decision.json"), {
    schema: "skill-rails/profile-decision/1",
    profile: selection.profile,
    explicit: selection.explicit,
    signals: selection.signals,
    warning: selection.profile === "p2" ? "This is a structurally valid design scaffold, not evidence that user-specific semantics are complete." : null
  });
  await writeJsonAtomic(join(root, ".skill-rails", "obligation-ledger.json"), createObligationLedger(intent, selection.profile));
  const cases = [
    ...(intent.use_cases ?? []).map((task, index) => ({
      id: `positive-${index + 1}`, task, should_trigger: true,
      expected_obligations: [...intent.outputs, ...intent.external_dependencies.map((item) => `Confirm dependency: ${item}`)],
      forbidden_actions: intent.irreversible_boundaries.map((item) => `Perform without explicit authority: ${item}`),
      acceptance: intent.completion_evidence.length > 0 ? [...intent.completion_evidence] : [...intent.outputs]
    })),
    ...(intent.near_misses ?? []).map((task, index) => ({ id: `near-miss-${index + 1}`, task, should_trigger: false, expected_obligations: [], forbidden_actions: [], acceptance: [] }))
  ];
  await writeJsonAtomic(join(root, ".skill-rails", "eval-cases.json"), cases);
}

async function writeOpenAiAdapter(root, intent, generated = false) {
  await mkdir(join(root, "agents"), { recursive: true });
  const header = generated ? "# @generated by Skill Rails\n" : "";
  await writeTextAtomic(join(root, "agents", "openai.yaml"), `${header}interface:\n  display_name: ${JSON.stringify(title(intent.name))}\n  short_description: ${JSON.stringify(shortDescription(intent.description))}\n  default_prompt: ${JSON.stringify(`Use $${intent.name} for this task and follow its evidence boundary.`)}\npolicy:\n  allow_implicit_invocation: true\n`);
}

async function writeReference(root, intent) {
  await mkdir(join(root, "references"), { recursive: true });
  await writeTextAtomic(join(root, "references", "intent.md"), `# Intent\n\nProblem: ${intent.problem}\n\n${renderIntentSections(intent)}\n`);
}

function p2Spec(intent) {
  return `export const SPEC = { version: "5", id: ${JSON.stringify(intent.name)}, profile: "single", imports: [] };
export const OBSERVATIONS = {
  "authoring.readiness": { decided: true, domain: ["ready", "needs-design", "complete"] }
};
export const FORMATS = {};
export const TEMPLATES = {
  result: { file: "templates/result.md", fields: { summary: "block" }, sections: [] }
};
export const ORDERS = {};
export const OWNERSHIP = {};
export const GUARDS = [];
export const STAGES = [
  { id: "operate", reads: ["authoring.readiness"], acceptsUnknown: [], done: s => s.authoring.readiness === "complete", needs: ["authoring.readiness"], reentry: "rejudge", branches: {
    ready: [["REPORT", { template: "result" }], "DONE"],
    "needs-design": ["BLOCK"]
  }, body: "stage: operate" }
];
export const TABLES = {};
export const ARTIFACTS = {};
export const ROLES = {};
export const READ_FIRST = [{ body: "why: purpose", path: "references/purpose.md" }];
export const DECLARATIONS = {
  profile: { value: "p2", consumer: "build:profile" }
};
export const DEFERRED = [{ id: "replace-authoring-scaffold", rule: "Replace the generic readiness stage with approved user-specific obligations.", collector: "none", fixture: "fixtures/scenarios.json", owner: ${JSON.stringify(intent.name)}, until: "before-behavior-verification" }];
`;
}

function p2Body(intent) {
  return `# ${title(intent.name)}\n\n## why: purpose\n\n${intent.problem.trim()}\n\n## stage: operate\n\nJudgment: authoring.readiness is one of ready, needs-design, or complete. Confirm that the user-specific contract has replaced the generic authoring scaffold before treating the skill as behavior-complete.\n\nWhy: Structural validity alone cannot prove that the user's intended behavior was preserved.\n`;
}

function p2Scenarios() {
  return [
    { id: "ready", s: {}, decided: { "authoring.readiness": "ready" }, expect: { stage: "operate", status: "DONE", effects: ["REPORT", "DONE"] }, cover: ["stage:operate", "branch:operate/ready"] },
    { id: "needs-design", s: {}, decided: { "authoring.readiness": "needs-design" }, expect: { stage: "operate", status: "BLOCK" }, cover: ["branch:operate/needs-design"] },
    { id: "complete", s: {}, decided: { "authoring.readiness": "complete" }, expect: { stage: null, status: "DONE" }, cover: [] }
  ];
}

function lintMutationCases() {
  const operations = [
    "extra-export", "ambient-authority", "observation-source", "invalid-domain", "reads-mismatch", "table-default",
    "stage-contract", "body-section", "body-duplicate-procedure", "stage-signature", "artifact-readers", "template-placeholder",
    "role-state-effect", "language-parity", "fixture-coverage", "format-domain", "deferred-shape", "mutation-manifest", "unsafe-bypass"
  ];
  return [
    ...operations.map((operation, index) => ({ id: `negative-L${index}`, expected_code: `L${index}`, mutation: { operation } })),
    { id: "negative-L15-format-golden", expected_code: "L15", mutation: { operation: "format-golden" } }
  ];
}

function workflowLines(intent) {
  const lines = [];
  for (const item of intent.use_cases ?? []) lines.push(`- Handle: ${item}`);
  for (const item of intent.completion_evidence ?? []) lines.push(`- Verify completion with: ${item}`);
  return lines.length > 0 ? lines : ["- Interpret the request against the recorded problem and produce the declared output."];
}

function renderIntentSections(intent) {
  return INTENT_ARRAYS.map((field) => `## ${title(field.replaceAll("_", "-"))}\n\n${bullets(intent[field])}`).join("\n\n");
}

function bullets(items = []) { return items.length > 0 ? items.map((item) => `- ${item}`).join("\n") : "- none"; }
function shortDescription(text) { return String(text).replace(/\s+/g, " ").trim().slice(0, 80); }
function title(name) { return String(name).split("-").map((part) => part ? part[0].toUpperCase() + part.slice(1) : part).join(" "); }

export { AUTHORING_ROOT };
